# Project metadata
name: online_tribes # Name of the Flutter project
description: A new Flutter project. # Description of the project
publish_to: "none" # Prevents publishing to pub.dev

# Versioning
version: 1.0.0+1 # Version number of the project

# Dart SDK environment
environment:
  sdk: ">=2.17.0 <3.0.0" # Specifies the version range of the Dart SDK

# Project dependencies
dependencies:
  flutter:
    sdk: flutter # Flutter SDK dependency

  # Routing
  go_router: ^14.1.0 # Package for declarative routing

  # Utility and helper packages
  flutter_gen_runner: ^5.4.0 # Generates code for assets, fonts, etc.

  # Firebase integration
  firebase_core: ^3.3.0 # Core Firebase functionality
  firebase_auth: ^5.1.4 # Firebase authentication
  firebase_storage: ^12.1.3 # Firebase cloud storage
  firebase_crashlytics: ^4.1.3
  cloud_firestore: ^5.2.1 # Cloud Firestore database
  google_sign_in_mocks: ^0.3.0
  firebase_analytics: ^11.2.1

  # Functional programming
  dartz: ^0.10.1 # Functional programming library for Dart

  # State management and dependency injection
  flutter_bloc: ^8.1.6 # BLoC pattern for state management
  get_it: ^7.7.0 # Dependency injection container
  injectable: ^2.4.4 # Code generation for dependency injection

  # Code generation and serialization
  freezed_annotation: ^2.4.4 # Annotations for immutable classes
  json_annotation: ^4.9.0 # Annotations for JSON serialization

  google_sign_in: ^6.2.1

  # Logging
  logger: ^2.4.0 # Logger utility for debugging
  equatable: ^2.0.5
  l10n_flutter: ^1.0.7
  flutter_localizations:
    sdk: flutter

  # Development dependencies
  shared_preferences: ^2.3.2
  flutter_markdown: ^0.7.3+1
  http: ^1.2.2
  wechat_assets_picker: ^9.2.1
  permission_handler: ^11.3.1
  wechat_camera_picker: ^4.3.2
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.4
  hive_flutter: ^1.1.0
  hive: any
  device_info_plus: ^10.1.2
  introduction_screen: ^3.1.14
  flutter_dotenv: ^5.1.0
  dio: ^5.7.0
  url_launcher: ^6.3.0
  uuid: ^4.5.0
  bloc: any
  intl: ^0.19.0

  # UI
  shimmer: ^3.0.0
  loading_indicator: any
  sign_in_button: ^3.2.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.11
  cached_network_image: ^3.4.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter # Flutter testing framework

  # Build and code generation
  build_runner: ^2.4.9 # Builds generated files

  go_router_builder: ^2.3.0 # Code generator for go_router
  flutter_lints: ^4.0.0 # Lints for Flutter projects
  freezed: ^2.5.7 # Code generator for immutable classes
  json_serializable: ^6.8.0 # JSON serialization code generator
  injectable_generator: ^2.6.2 # Code generator for injectable
  integration_test:
    sdk: flutter
  mockito: ^5.4.4

  firebase_storage_mocks: ^0.7.0
  fake_cloud_firestore: ^3.0.2
  firebase_auth_mocks: ^0.14.0

# Flutter-specific settings
flutter:
  uses-material-design: true # Enables Material Design icons
  generate: true

  # Assets configuration
  assets:
    - assets/authetication/
    - assets/registration/
    - assets/shared/
    - assets/shared/drawer/
    - assets/shared/logo/
    - assets/shared/fake_tribe_profile_gallery/
    - assets/shared/fake_user_avatar/
    - assets/shared/icons/
    - assets/populate_json/
    - assets/banner/
    - .env

# FlutterGen configuration
flutter_gen:
  output: lib/gen/ # Directory for generated files
  integrations:
    flutter_svg: true # Enables SVG integration

  # Asset management
  assets:
    enabled: true # Enables asset generation
    style: camelCase # Style of generated asset names
